[RFC] Implement display_order handling for form fields
1up-lab/contao-mailchimp pull request #7
Opened 2017-09-26 19:03 UTC by bezin

Hi there, 

as discussed in #6 , the implementation should respect the order of the form fields, that can be changed in the MailChimp interface. This PR takes care of this.

One known issue is, that since the email field itself is still not included in the API response, the chosen email field label in MailChimp is obviously not available in Contao. It still has to be changed through the language array, as it was prior to this PR. 

Let me know what you all think :)

Cheers!

2017-09-26 20:43 UTC, bytehead commented
Thank you for the PR! I'll review this asap.

2017-09-26 21:06 UTC, bytehead requested changes
Mostly code style (CS) issues. Aside of this, the PR looks good to me! Thank you very much!

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Model/MailChimpModel.php
> +                    'display_order' => $rawField->display_order,
Just for CS reasons: please change this line to `'displayOrder' => $rawField->display_order,`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            return ($a->display_order > $b->display_order) ? 1 : -1;
Just for CS reasons: please change this line to `return ($a->displayOrder > $b->displayOrder) ? 1 : -1;`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            'display_order' => -1,
Just for CS reasons: please change this line to `'displayOrder' => -1,`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +        if ($fields[0]->display_order === 2) {
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            $email->display_order = 1;
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +        if ($fields[0]->display_order === 2) {
Just for CS reasons: please use yoda conditions `if (2 === $fields[0]->displayOrder) {`

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            $index = $fields[0]->display_order;
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +                if ($field->display_order === ($index + 1)) {
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +                if ($field->display_order === ($index + 1)) {
Just for CS reasons: please use yoda conditions `if (($index + 1) === $field->displayOrder) {`

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +                    $email->display_order = $index;
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            if ($email->display_order === -1) {
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            if ($email->display_order === -1) {
Just for CS reasons: please use yoda conditions `if (-1 === $email->displayOrder) {`

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +                $email->display_order = (count($fields) + 1);
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +        array_splice($fields, ($email->display_order - 1), 0, [$email]);
Just for CS reasons: please change `display_order` to `displayOrder`.

2017-09-26 21:06 UTC, bytehead commented on src/MailChimp/Module/ModuleSubscribe.php
> +            case 'email':
Duplicate `case 'email':` here, probably overseen here 🙂

2017-09-27 05:58 UTC, bytehead commented
It would also be nice to have some kind of hint in the `README.md`, how to sort the fields:
> You can not change order in Settings-->List fields and |MERGE| tags but you can in Signup forms --> General forms --> Signup form
> 
> The order you pick here (drag'n'drop) will also be visible in the |MERGE| tags view.

2017-09-27 07:08 UTC, bezin commented
Thanks for your comments. I updated the PR accordingly.

2017-09-27 07:17 UTC, bytehead commented
Thank you for the quick changes!

2017-09-27 07:19 UTC, bytehead approved these changes

2017-09-27 07:21 UTC, bytehead commented
I'll have to release a new major version (`3.0.0`) because of the not backward compatible changes.

2017-09-27 07:22 UTC, merged